# Generated by Django 5.0.4 on 2024-05-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(default='1234', max_length=255)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('dept_name', models.CharField(blank=True, max_length=32, null=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(default='1234', max_length=255)),
            ],
            options={
                'db_table': 'Credentials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('building', models.CharField(blank=True, max_length=255, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('dept_name', models.CharField(blank=True, max_length=10, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=8)),
                ('sec_id', models.CharField(max_length=4)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('building', models.CharField(blank=True, max_length=32, null=True)),
                ('room', models.CharField(blank=True, max_length=8, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('dept_name', models.CharField(blank=True, max_length=32, null=True)),
                ('total_credits', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Takes',
            fields=[
                ('student_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=8)),
                ('sec_id', models.CharField(max_length=4)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('course_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('sec_id', models.CharField(max_length=4)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('teacher_id', models.CharField(max_length=5)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
